### ISSUE TITLE
list index error range using interactive mode of reaper

### ISSUE THREAD

**Issue by davidallenmann** [humulabs/reaper#21]
Using SD formatted on PC (also tried on Mac).
One file on card: test.txt

sdreaper -p /dev/tty.usbmodem1421 'ls' works

```
% sdreaper -p /dev/tty.usbmodem1421 'ls'
connecting to /dev/tty.usbmodem1421 at 9600 baud...

connected to /dev/tty.usbmodem1421 at 9600 baud.
2016-03-29 08:05:52          0 System Volume Information/
  2016-03-29 08:05:52         76 IndexerVolumeGuid
2000-01-01 01:00:00         18 test.txt
```

When run in interactive mode and enter 'r' get error

```
% sdreaper -p /dev/tty.usbmodem1421
connecting to /dev/tty.usbmodem1421 at 9600 baud...
......................
connected to /dev/tty.usbmodem1421 at 9600 baud.
Traceback (most recent call last):
  File "/Users/dmann/miniconda3/bin/sdreaper", line 11, in <module>
    sys.exit(main())
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/sdreaper/main.py", line 59, in main
    App(reaper)
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/sdreaper/app.py", line 84, in __init__
    self.loop.run()
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/main_loop.py", line 509, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/urwid/main_loop.py", line 555, in unhandled_input
    return self._unhandled_input(input)
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/sdreaper/app.py", line 78, in keypress
    self.download()
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/sdreaper/app.py", line 92, in download
    files = self.reaper.ls()
  File "/Users/dmann/miniconda3/lib/python3.4/site-packages/sdreaper/reaper.py", line 147, in ls
    size=int(fields[1]),
IndexError: list index out of range
```

**Comment by davidallenmann** [comment]
also get error when have two files on card

**Comment by davidallenmann** [comment]
needed to do make install
